version: '3'
services:
  mysql:
    image: mysql:8.0.13
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: db
      MYSQL_USER: user
  
