// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/code.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_code_757e3851d178bb31, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type CodeFile struct {
	FileName             string   `protobuf:"bytes,1,opt,name=file_name,json=fileName" json:"file_name,omitempty"`
	Body                 []byte   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CodeFile) Reset()         { *m = CodeFile{} }
func (m *CodeFile) String() string { return proto.CompactTextString(m) }
func (*CodeFile) ProtoMessage()    {}
func (*CodeFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_code_757e3851d178bb31, []int{1}
}
func (m *CodeFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeFile.Unmarshal(m, b)
}
func (m *CodeFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeFile.Marshal(b, m, deterministic)
}
func (dst *CodeFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeFile.Merge(dst, src)
}
func (m *CodeFile) XXX_Size() int {
	return xxx_messageInfo_CodeFile.Size(m)
}
func (m *CodeFile) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeFile.DiscardUnknown(m)
}

var xxx_messageInfo_CodeFile proto.InternalMessageInfo

func (m *CodeFile) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *CodeFile) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type VmissRequest struct {
	BuildDir             string      `protobuf:"bytes,2,opt,name=build_dir,json=buildDir" json:"build_dir,omitempty"`
	Files                []*CodeFile `protobuf:"bytes,1,rep,name=files" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *VmissRequest) Reset()         { *m = VmissRequest{} }
func (m *VmissRequest) String() string { return proto.CompactTextString(m) }
func (*VmissRequest) ProtoMessage()    {}
func (*VmissRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_code_757e3851d178bb31, []int{2}
}
func (m *VmissRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VmissRequest.Unmarshal(m, b)
}
func (m *VmissRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VmissRequest.Marshal(b, m, deterministic)
}
func (dst *VmissRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VmissRequest.Merge(dst, src)
}
func (m *VmissRequest) XXX_Size() int {
	return xxx_messageInfo_VmissRequest.Size(m)
}
func (m *VmissRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VmissRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VmissRequest proto.InternalMessageInfo

func (m *VmissRequest) GetBuildDir() string {
	if m != nil {
		return m.BuildDir
	}
	return ""
}

func (m *VmissRequest) GetFiles() []*CodeFile {
	if m != nil {
		return m.Files
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "proto.Empty")
	proto.RegisterType((*CodeFile)(nil), "proto.CodeFile")
	proto.RegisterType((*VmissRequest)(nil), "proto.VmissRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VmissRPCClient is the client API for VmissRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VmissRPCClient interface {
	StoreFiles(ctx context.Context, in *VmissRequest, opts ...grpc.CallOption) (*Empty, error)
}

type vmissRPCClient struct {
	cc *grpc.ClientConn
}

func NewVmissRPCClient(cc *grpc.ClientConn) VmissRPCClient {
	return &vmissRPCClient{cc}
}

func (c *vmissRPCClient) StoreFiles(ctx context.Context, in *VmissRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.VmissRPC/StoreFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VmissRPC service

type VmissRPCServer interface {
	StoreFiles(context.Context, *VmissRequest) (*Empty, error)
}

func RegisterVmissRPCServer(s *grpc.Server, srv VmissRPCServer) {
	s.RegisterService(&_VmissRPC_serviceDesc, srv)
}

func _VmissRPC_StoreFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VmissRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmissRPCServer).StoreFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VmissRPC/StoreFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmissRPCServer).StoreFiles(ctx, req.(*VmissRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VmissRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.VmissRPC",
	HandlerType: (*VmissRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreFiles",
			Handler:    _VmissRPC_StoreFiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/code.proto",
}

func init() { proto.RegisterFile("proto/code.proto", fileDescriptor_code_757e3851d178bb31) }

var fileDescriptor_code_757e3851d178bb31 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xce, 0x4f, 0x49, 0xd5, 0x03, 0x33, 0x85, 0x58, 0xc1, 0x94, 0x12, 0x3b, 0x17,
	0xab, 0x6b, 0x6e, 0x41, 0x49, 0xa5, 0x92, 0x35, 0x17, 0x87, 0x73, 0x7e, 0x4a, 0xaa, 0x5b, 0x66,
	0x4e, 0xaa, 0x90, 0x34, 0x17, 0x67, 0x5a, 0x66, 0x4e, 0x6a, 0x7c, 0x5e, 0x62, 0x6e, 0xaa, 0x04,
	0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x07, 0x48, 0xc0, 0x2f, 0x31, 0x37, 0x55, 0x48, 0x88, 0x8b,
	0x25, 0x29, 0x3f, 0xa5, 0x52, 0x82, 0x59, 0x81, 0x51, 0x83, 0x27, 0x08, 0xcc, 0x56, 0x0a, 0xe2,
	0xe2, 0x09, 0xcb, 0xcd, 0x2c, 0x2e, 0x0e, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x01, 0x19, 0x90,
	0x54, 0x9a, 0x99, 0x93, 0x12, 0x9f, 0x92, 0x59, 0x24, 0xc1, 0x04, 0x31, 0x00, 0x2c, 0xe0, 0x92,
	0x59, 0x24, 0xa4, 0xca, 0xc5, 0x0a, 0x32, 0xac, 0x58, 0x82, 0x51, 0x81, 0x59, 0x83, 0xdb, 0x88,
	0x1f, 0xe2, 0x20, 0x3d, 0x98, 0xed, 0x41, 0x10, 0x59, 0x23, 0x6b, 0x2e, 0x0e, 0x88, 0x99, 0x01,
	0xce, 0x42, 0xfa, 0x5c, 0x5c, 0xc1, 0x25, 0xf9, 0x45, 0x60, 0xf9, 0x62, 0x21, 0x61, 0xa8, 0x0e,
	0x64, 0x2b, 0xa5, 0x78, 0xa0, 0x82, 0x60, 0xdf, 0x24, 0xb1, 0x81, 0x39, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x00, 0x44, 0xe1, 0x38, 0xf8, 0x00, 0x00, 0x00,
}
